tabla = read.table("estad_descriptiva.txt", header = TRUE)
mean(c(tabla[,1]))
mean(c(tabla[,2]))
mean(c(tabla[,3]))
median(c(tabla[,1]))
median(c(tabla[,2]))
median(c(tabla[,3]))
mean(c(tabla[,1]), trim = 0.1)
mean(c(tabla[,1]), trim = 0.2)
mean(c(tabla[,2]), trim = 0.1)
mean(c(tabla[,2]), trim = 0.2)
mean(c(tabla[,3]), trim = 0.1)
mean(c(tabla[,3]), trim = 0.2)
sd(c(tabla[,1]))
sd(c(tabla[,2]))
sd(c(tabla[,3]))
IQR(c(tabla[,1]))
IQR(c(tabla[,2]))
IQR(c(tabla[,3]))
quantile(c(tabla[,1]), c(.1, .25, .5, .75, .9))
quantile(c(tabla[,2]), c(.1, .25, .5, .75, .9))
quantile(c(tabla[,3]), c(.1, .25, .5, .75, .9))
hist(tabla[,1])
hist(tabla[,2])
hist(tabla[,3])
hist(tabla[,3][tabla[,3]<=quantile(tabla[,3],.9)])
boxplot(tabla[,1])
boxplot(tabla[,2])
boxplot(tabla[,3])
boxplot(tabla[,3][tabla[,3]<=quantile(tabla[,3],.9)])